# Generated by Django 5.1 on 2024-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cratefrom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_query', models.CharField(max_length=50)),
            ],
        ),
    ]
